create database house_shuffler;
use house_shuffler;

CREATE TABLE students (
    admno INT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    grade VARCHAR(12),
    house ENUM('Fathima', 'Montfort', 'Joseph', 'Gabriel')
);

INSERT INTO students (admno, name, grade, house) VALUES
(1, 'Aryan Kumar', '10 D', 'Fathima'),
(2, 'Neha Sharma', '10 D', 'Montfort'),
(3, 'Rahul Menon', '10 D', 'Joseph'),
(4, 'Anjali Nair', '10 D', 'Gabriel'),
(5, 'Aditi Das', '10 D', 'Fathima'),
(6, 'Vikram Iyer', '10 D', 'Montfort'),
(7, 'Priya Pillai', '10 D', 'Joseph'),
(8, 'Kavya Joseph', '10 D', 'Gabriel'),
(9, 'Arjun Thomas', '10 D', 'Fathima'),
(10, 'Nandini Singh', '10 D', 'Montfort'),
(11, 'Shreya Verma', '10 D', 'Joseph'),
(12, 'Vivek Kumar', '10 D', 'Gabriel'),
(13, 'Aishwarya Nair', '10 D', 'Fathima'),
(14, 'Manoj Pillai', '10 D', 'Montfort'),
(15, 'Sneha Joseph', '10 D', 'Joseph'),
(16, 'Rohit Menon', '10 D', 'Gabriel'),
(17, 'Meera Thomas', '10 D', 'Fathima'),
(18, 'Karthik Iyer', '10 D', 'Montfort'),
(19, 'Lavanya Menon', '10 D', 'Joseph'),
(20, 'Ajay Kumar', '10 D', 'Gabriel'),
(21, 'Ishita Nair', '10 D', 'Fathima'),
(22, 'Saurav Sen', '10 D', 'Montfort'),
(23, 'Nikhil Menon', '10 D', 'Joseph'),
(24, 'Diya Pillai', '10 D', 'Gabriel'),
(25, 'Ankit Sharma', '10 D', 'Fathima'),
(26, 'Snehalatha Iyer', '10 D', 'Montfort'),
(27, 'Vishnu Kumar', '10 D', 'Joseph'),
(28, 'Ravi Thomas', '10 D', 'Gabriel'),
(29, 'Anuja Nair', '10 D', 'Fathima'),
(30, 'Kiran Sharma', '10 D', 'Montfort'),
(31, 'Anusha Menon', '10 D', 'Joseph'),
(32, 'Harsha Iyer', '10 D', 'Gabriel'),
(33, 'Manish Kumar', '10 D', 'Fathima'),
(34, 'Divya Sen', '10 D', 'Montfort'),
(35, 'Akhil Menon', '10 D', 'Joseph'),
(36, 'Nisha Thomas', '10 D', 'Gabriel'),
(37, 'Rahul Sharma', '10 D', 'Fathima'),
(38, 'Praveen Menon', '10 D', 'Montfort'),
(39, 'Keerthana Iyer', '10 D', 'Joseph'),
(40, 'Ashwin Kumar', '10 D', 'Gabriel');


CREATE TABLE achievements (
    admno INT,
    name VARCHAR(30) NOT NULL,
    grade VARCHAR(12),
    house VARCHAR(8),
    event ENUM('Javelin Throw',  'Discus Throw',  '1500 meters',  'Long Jump', 'Shotput', '100 meters', '200 meters', '400 meters', '800 meters', '4x100 meters Relay', '4x400 meters Relay'),
    position ENUM('I', 'II', 'III'),
    FOREIGN KEY (admno) REFERENCES students(admno)
);

-- Insert achievements records for participating students
INSERT INTO achievements (admno, name, grade, house, event, position) VALUES
(1, 'Aryan Kumar', '10 D', 'Fathima', '100 meters', 'I'),
(1, 'Aryan Kumar', '10 D', 'Fathima', '200 meters', 'II'),
(1, 'Aryan Kumar', '10 D', 'Fathima', '4x100 meters Relay', 'I'),
(2, 'Neha Sharma', '10 D', 'Montfort', 'Shotput', 'III'),
(2, 'Neha Sharma', '10 D', 'Montfort', 'Discus Throw', 'I'),
(3, 'Rahul Menon', '10 D', 'Joseph', 'Long Jump', 'II'),
(3, 'Rahul Menon', '10 D', 'Joseph', '1500 meters', 'III'),
(4, 'Anjali Nair', '10 D', 'Gabriel', 'Javelin Throw', 'I'),
(4, 'Anjali Nair', '10 D', 'Gabriel', '400 meters', 'II'),
(5, 'Aditi Das', '10 D', 'Fathima', 'Discus Throw', 'I'),
(5, 'Aditi Das', '10 D', 'Fathima', 'Shotput', 'III'),
(6, 'Vikram Iyer', '10 D', 'Montfort', '4x100 meters Relay', 'I'),
(6, 'Vikram Iyer', '10 D', 'Montfort', '4x400 meters Relay', 'II'),
(7, 'Priya Pillai', '10 D', 'Joseph', '1500 meters', 'II'),
(7, 'Priya Pillai', '10 D', 'Joseph', '800 meters', 'III'),
(8, 'Kavya Joseph', '10 D', 'Gabriel', '4x100 meters Relay', 'I'),
(8, 'Kavya Joseph', '10 D', 'Gabriel', '4x400 meters Relay', 'II'),
(11, 'Shreya Verma', '10 D', 'Joseph', '100 meters', 'III'),
(11, 'Shreya Verma', '10 D', 'Joseph', '200 meters', 'I'),
(12, 'Vivek Kumar', '10 D', 'Gabriel', 'Javelin Throw', 'II'),
(12, 'Vivek Kumar', '10 D', 'Gabriel', '400 meters', 'III'),
(13, 'Aishwarya Nair', '10 D', 'Fathima', 'Long Jump', 'I'),
(13, 'Aishwarya Nair', '10 D', 'Fathima', '1500 meters', 'II'),
(14, 'Manoj Pillai', '10 D', 'Montfort', '4x400 meters Relay', 'III'),
(14, 'Manoj Pillai', '10 D', 'Montfort', '800 meters', 'I'),
(15, 'Sneha Joseph', '10 D', 'Joseph', '200 meters', 'II'),
(15, 'Sneha Joseph', '10 D', 'Joseph', '100 meters', 'III'),
(16, 'Rohit Menon', '10 D', 'Gabriel', 'Discus Throw', 'I'),
(16, 'Rohit Menon', '10 D', 'Gabriel', 'Shotput', 'II'),
(17, 'Meera Thomas', '10 D', 'Fathima', '400 meters', 'III'),
(17, 'Meera Thomas', '10 D', 'Fathima', '4x100 meters Relay', 'I'),
(18, 'Karthik Iyer', '10 D', 'Montfort', '800 meters', 'II'),
(18, 'Karthik Iyer', '10 D', 'Montfort', '4x400 meters Relay', 'III'),
(19, 'Lavanya Menon', '10 D', 'Joseph', '100 meters', 'I'),
(19, 'Lavanya Menon', '10 D', 'Joseph', '200 meters', 'II'),
(21, 'Ishita Nair', '10 D', 'Fathima', '1500 meters', 'III'),
(21, 'Ishita Nair', '10 D', 'Fathima', '4x100 meters Relay', 'I'),
(22, 'Saurav Sen', '10 D', 'Montfort', 'Long Jump', 'II'),
(22, 'Saurav Sen', '10 D', 'Montfort', '400 meters', 'III'),
(23, 'Nikhil Menon', '10 D', 'Joseph', 'Javelin Throw', 'I'),
(23, 'Nikhil Menon', '10 D', 'Joseph', 'Discus Throw', 'II'),
(25, 'Ankit Sharma', '10 D', 'Fathima', '4x400 meters Relay', 'III'),
(25, 'Ankit Sharma', '10 D', 'Fathima', '1500 meters', 'I'),
(27, 'Vishnu Kumar', '10 D', 'Joseph', 'Shotput', 'II'),
(27, 'Vishnu Kumar', '10 D', 'Joseph', '200 meters', 'III'),
(28, 'Ravi Thomas', '10 D', 'Gabriel', '4x100 meters Relay', 'I'),
(28, 'Ravi Thomas', '10 D', 'Gabriel', '4x400 meters Relay', 'II'),
(30, 'Kiran Sharma', '10 D', 'Montfort', '800 meters', 'III'),
(30, 'Kiran Sharma', '10 D', 'Montfort', '1500 meters', 'I');

-- Insert NULL values for students with no achievements
INSERT INTO achievements (admno, name, grade, house, event, position) VALUES
(9, 'Arjun Thomas', '10 D', 'Fathima', NULL, NULL),
(10, 'Nandini Singh', '10 D', 'Montfort', NULL, NULL),
(20, 'Ajay Kumar', '10 D', 'Gabriel', NULL, NULL),
(24, 'Diya Pillai', '10 D', 'Gabriel', NULL, NULL),
(26, 'Snehalatha Iyer', '10 D', 'Montfort', NULL, NULL),
(29, 'Anuja Nair', '10 D', 'Fathima', NULL, NULL),
(31, 'Anusha Menon', '10 D', 'Joseph', NULL, NULL),
(32, 'Harsha Iyer', '10 D', 'Gabriel', NULL, NULL),
(33, 'Manish Kumar', '10 D', 'Fathima', NULL, NULL),
(34, 'Divya Sen', '10 D', 'Montfort', NULL, NULL),
(35, 'Akhil Menon', '10 D', 'Joseph', NULL, NULL),
(36, 'Nisha Thomas', '10 D', 'Gabriel', NULL, NULL),
(37, 'Rahul Sharma', '10 D', 'Fathima', NULL, NULL),
(38, 'Praveen Menon', '10 D', 'Montfort', NULL, NULL),
(39, 'Keerthana Iyer', '10 D', 'Joseph', NULL, NULL),
(40, 'Ashwin Kumar', '10 D', 'Gabriel', NULL, NULL);
